name: ProtectionStones
version: ${version}
description: ${description} - Translated and improved version for Crafterz.ee
authors: [Vik1395,Dragoboss,Jarzean,Dylan-BukkitPlugins,EspiDev,mikroskeem,ArdiK_,kaimokene]
website: https://github.com/mikroskeem/ProtectionStones-Minecraft

depend: [WorldGuard, WorldEdit]
main: me.vik1395.ProtectionStones.ProtectionStones
api-version: 1.13

commands:
  ps:
    description: Base command for protection stones.
    aliases: [protectionstone, protectionstones, pstone]
    usage: /ps help